# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings
name: Uncle Auggie's | Handcrafted Vermont Pomade
description: ""
url: "https://www.shelter2rescue.org"
authors:
  - name: "Paul Detzer"
    email: "paul.detzer@gmail.com"
    github_username: "sirgeraldo1"

  - name: "Akhil Rao"
    email: "akhiloar@gmail.com"
    github_username: "furuutsuponchisamurai"

# Build settings
baseurl: ""
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
source: .
destination: ./_site
incremental: true

# Options
keep_files: [images, assets]
